s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.upper())
print(s.lower())
print("python programing".title())
print(s.swapcase())
print(s.center(50,"*"))
print(s.count("o"))
print(s.endswith("es"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(s.istitle())
print("TOPS".isupper())
print("tops".islower())
print(" ".isspace())
print("Hello".replace("l","w"))
